// <auto-generated />
using System;
using BackendApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(RodjendanDb))]
    [Migration("20250322090250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BackendApi.Models.Rodjendan", b =>
                {
                    b.Property<int>("Sifra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojGostiju")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Cijena")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Kapara")
                        .HasColumnType("REAL");

                    b.Property<bool?>("KaparaPlacena")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KrajDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Paket")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlavljenikSifra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Sifra");

                    b.HasIndex("SlavljenikSifra");

                    b.ToTable("Rodjendani");
                });

            modelBuilder.Entity("BackendApi.Models.Slavljenik", b =>
                {
                    b.Property<int>("Sifra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Sifra");

                    b.ToTable("Slavljenici");
                });

            modelBuilder.Entity("BackendApi.Models.Rodjendan", b =>
                {
                    b.HasOne("BackendApi.Models.Slavljenik", "SlavljenikNavigation")
                        .WithMany("Rodjendani")
                        .HasForeignKey("SlavljenikSifra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlavljenikNavigation");
                });

            modelBuilder.Entity("BackendApi.Models.Slavljenik", b =>
                {
                    b.Navigation("Rodjendani");
                });
#pragma warning restore 612, 618
        }
    }
}
